name: MelodySnippets

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.*
  - pip=19.2.*
  - numpy=1.17.*
  - scipy=1.3.*
  - ffmpeg=2.8.*
  - numba=0.45.*
  - pip:
    - nbstripout==0.3.*
    - music21==5.7.*
    - librosa==0.8.*
    - pysoundfile==0.9.*
    - resampy==0.2.*
    - midiutil==1.2.*
    - argparse==1.4.*
    - vamp==1.1.*
    - flask==1.1.2
    - flask-cors==3.0.9
